"""
exporter.py — Export best backtest results to production config.

Reads backtest scan results (from BacktestRunner.scan_all() or
GridSearchTuner), ranks strategies per (asset, frequency),
and generates a StrategyConfig-based Python module.
"""

from __future__ import annotations

import json
import os
from datetime import datetime
from pathlib import Path
from typing import Optional

from synth.miner.strategies.base import StrategyConfig


# Default output path for the generated config
_DEFAULT_OUTPUT = "synth/miner/config/asset_strategy_config.py"


def export_best_config(
    scan_results: list[dict],
    top_n: int = 3,
    output_path: str = _DEFAULT_OUTPUT,
    backup: bool = True,
    min_successful_runs: int = 2,
) -> dict[tuple[str, str], list[StrategyConfig]]:
    """
    From backtest scan results, pick top N strategies per (asset, frequency),
    compute weights proportional to inverse score, and write the config file.

    Args:
        scan_results: List of benchmark result dicts from BacktestRunner.scan_all()
            Each dict must have: strategy, asset, frequency, avg_score, successful_runs
        top_n: Number of top strategies per (asset, freq) to include.
        output_path: Where to write the generated config module.
        backup: If True, backup existing config before overwriting.
        min_successful_runs: Minimum successful runs to consider a result valid.

    Returns:
        The generated config dict.
    """
    # Group results by (asset, frequency)
    grouped: dict[tuple[str, str], list[dict]] = {}
    for result in scan_results:
        if result.get("successful_runs", 0) < min_successful_runs:
            continue
        if result.get("avg_score", float("inf")) == float("inf"):
            continue

        key = (result["asset"], result["frequency"])
        if key not in grouped:
            grouped[key] = []
        grouped[key].append(result)

    # Rank and select top N per group
    config: dict[tuple[str, str], list[StrategyConfig]] = {}

    for key, results in grouped.items():
        # Sort by avg_score (lower is better)
        sorted_results = sorted(results, key=lambda r: r["avg_score"])
        top_results = sorted_results[:top_n]

        if not top_results:
            continue

        # Compute weights: inverse of score, normalized
        scores = [r["avg_score"] for r in top_results]
        inverse_scores = [1.0 / max(s, 1e-6) for s in scores]
        total_inv = sum(inverse_scores)

        strategy_configs = []
        for result, inv_score in zip(top_results, inverse_scores):
            weight = round(inv_score / total_inv, 2)
            sc = StrategyConfig(
                strategy_name=result["strategy"],
                weight=weight,
                params=result.get("kwargs", {}),
            )
            strategy_configs.append(sc)

        config[key] = strategy_configs

    # Write the config file
    if output_path:
        _write_config_module(config, output_path, backup)

    # Also save raw JSON for audit trail
    _save_audit_json(config, scan_results, output_path)

    return config


def _write_config_module(
    config: dict[tuple[str, str], list[StrategyConfig]],
    output_path: str,
    backup: bool,
) -> None:
    """Generate a Python module from the config dict."""

    if backup and os.path.exists(output_path):
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        backup_path = f"{output_path}.bak.{ts}"
        os.rename(output_path, backup_path)
        print(f"[Export] Backed up existing config to {backup_path}")

    lines = [
        '"""',
        "asset_strategy_config.py — Auto-generated production strategy-asset mappings.",
        "",
        f"Generated by deploy/exporter.py on {datetime.now().isoformat()}",
        "Tip: Edit manually or re-run exporter after backtesting.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from synth.miner.strategies.base import StrategyConfig",
        "",
        "",
        "PRODUCTION_CONFIG: dict[tuple[str, str], list[StrategyConfig]] = {",
    ]

    # Sort keys for consistent output
    for key in sorted(config.keys()):
        asset, freq = key
        configs = config[key]
        lines.append(f'    ("{asset}", "{freq}"): [')
        for sc in configs:
            params_str = f", params={sc.params}" if sc.params else ""
            lines.append(
                f'        StrategyConfig("{sc.strategy_name}", weight={sc.weight}{params_str}),'
            )
        lines.append("    ],")

    lines.append("}")
    lines.append("")

    # Add fallback chain
    lines.extend([
        "",
        "DEFAULT_FALLBACK_CHAIN: list[str] = [",
        '    "garch_v2",',
        '    "garch_v4",',
        '    "garch_v4_1",',
        '    "garch_v4_2",',
        '    "egarch",',
        '    "garch_v2_1",',
        '    "seasonal_stock",',
        '    "garch_v1",',
        '    "har_rv",',
        "]",
        "",
        "",
        "def get_strategy_list(",
        "    asset: str, time_length: int",
        ") -> list[StrategyConfig]:",
        '    """Retrieve the production strategy list for a given asset and time_length."""',
        "    from synth.miner.config.defaults import get_prompt_type",
        "",
        "    freq = get_prompt_type(time_length)",
        "    key = (asset, freq)",
        "",
        "    if key in PRODUCTION_CONFIG:",
        "        return list(PRODUCTION_CONFIG[key])",
        "",
        '    key_low = (asset, "low")',
        "    if key_low in PRODUCTION_CONFIG:",
        "        return list(PRODUCTION_CONFIG[key_low])",
        "",
        "    n = 3",
        "    w = round(1.0 / n, 2)",
        "    return [",
        "        StrategyConfig(name, weight=w)",
        "        for name in DEFAULT_FALLBACK_CHAIN[:n]",
        "    ]",
        "",
    ])

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write("\n".join(lines))

    print(f"[Export] Wrote config to {output_path} ({len(config)} entries)")


def _save_audit_json(
    config: dict[tuple[str, str], list[StrategyConfig]],
    scan_results: list[dict],
    output_path: str,
) -> None:
    """Save raw JSON audit trail alongside the config."""
    audit = {
        "timestamp": datetime.now().isoformat(),
        "config": {
            f"{k[0]}_{k[1]}": [
                {"name": sc.strategy_name, "weight": sc.weight, "params": sc.params}
                for sc in v
            ]
            for k, v in config.items()
        },
        "top_results_summary": [
            {
                "strategy": r.get("strategy"),
                "asset": r.get("asset"),
                "frequency": r.get("frequency"),
                "avg_score": r.get("avg_score"),
                "median_score": r.get("median_score"),
                "successful_runs": r.get("successful_runs"),
            }
            for r in scan_results
            if r.get("avg_score", float("inf")) != float("inf")
        ],
    }

    audit_path = output_path.replace(".py", "_audit.json")
    with open(audit_path, "w") as f:
        json.dump(audit, f, indent=2, default=str)
    print(f"[Export] Audit trail saved to {audit_path}")
