"""
asset_strategy_config.py — Production strategy-asset mappings.

Replaces the hardcoded STRATEGY_LIST_FOR_ASSET dict from simulations_new_v3.py.
Uses StrategyConfig dataclass for type-safe, version-tracked configuration.

This file is the SINGLE SOURCE OF TRUTH for which strategies run in production.
It is auto-generated by deploy/exporter.py and can also be edited manually.
"""

from __future__ import annotations

from synth.miner.strategies.base import StrategyConfig


# ─────────────────────────────────────────────────────────────────────
# Production Config: (asset, frequency) -> list of StrategyConfig
# ─────────────────────────────────────────────────────────────────────
PRODUCTION_CONFIG: dict[tuple[str, str], list[StrategyConfig]] = {
    # ── HIGH frequency (time_length=3600) ────────────────────────────
    ("BTC", "high"): [StrategyConfig("dynamic_router", weight=1.0)],
    ("ETH", "high"): [StrategyConfig("dynamic_router", weight=1.0)],
    ("XAU", "high"): [StrategyConfig("garch_v4_1", weight=1.0)],
    ("SOL", "high"): [StrategyConfig("dynamic_router", weight=1.0)],

    # ── LOW frequency (time_length=86400) ────────────────────────────
    ("BTC", "low"): [
        StrategyConfig("dynamic_router", weight=0.6),
        StrategyConfig("garch_v2_2", weight=0.4),
    ],
    ("ETH", "low"): [
        StrategyConfig("dynamic_router", weight=0.6),
        StrategyConfig("regime_switching", weight=0.4),
    ],
    ("XAU", "low"): [
        StrategyConfig("jump_diffusion", weight=0.4),
        StrategyConfig("garch_v4_1", weight=0.3),
        StrategyConfig("weekly_regime_switching", weight=0.3),
    ],
    ("SOL", "low"): [
        StrategyConfig("dynamic_router", weight=0.6),
        StrategyConfig("arima_equity", weight=0.4),
    ],

    # ── Stocks (LOW frequency only) ─────────────────────────────────
    ("NVDAX", "low"): [
        StrategyConfig("arima_equity", weight=0.4),
        StrategyConfig("garch_v4_1", weight=0.3),
        StrategyConfig("markov_garch_jump", weight=0.3),
    ],
    ("TSLAX", "low"): [
        StrategyConfig("weekly_garch_v4", weight=0.4),
        StrategyConfig("garch_v4", weight=0.3),
        StrategyConfig("regime_switching", weight=0.3),
    ],
    ("AAPLX", "low"): [
        StrategyConfig("markov_garch_jump", weight=0.4),
        StrategyConfig("regime_switching", weight=0.3),
        StrategyConfig("garch_v4_1", weight=0.3),
    ],
    ("GOOGLX", "low"): [
        StrategyConfig("weekly_regime_switching", weight=0.4),
        StrategyConfig("garch_v4_1", weight=0.3),
        StrategyConfig("regime_switching", weight=0.3),
    ],
    ("SPYX", "low"): [
        StrategyConfig("weekly_regime_switching", weight=0.4),
        StrategyConfig("garch_v4", weight=0.3),
        StrategyConfig("arima_equity", weight=0.3),
    ],
}


# ─────────────────────────────────────────────────────────────────────
# Default fallback chain (used when no config exists for an asset)
# ─────────────────────────────────────────────────────────────────────
DEFAULT_FALLBACK_CHAIN: list[str] = [
    "garch_v2",
    "garch_v4",
    "garch_v4_1",
    "garch_v4_2",
    "egarch",
    "garch_v2_1",
    "seasonal_stock",
    "garch_v1",
    "har_rv",
]


# ─────────────────────────────────────────────────────────────────────
# Helper: get strategy list for a given (asset, time_length)
# ─────────────────────────────────────────────────────────────────────
def get_strategy_list(
    asset: str, time_length: int
) -> list[StrategyConfig]:
    """
    Retrieve the production strategy list for a given asset and time_length.

    Falls back in this order:
        1. Exact (asset, frequency) match
        2. (asset, "low") match (if freq is unknown)
        3. Default fallback with equal weights
    """
    from synth.miner.config.defaults import get_prompt_type

    freq = get_prompt_type(time_length)
    key = (asset, freq)

    if key in PRODUCTION_CONFIG:
        return list(PRODUCTION_CONFIG[key])

    # Fallback: try "low" frequency
    key_low = (asset, "low")
    if key_low in PRODUCTION_CONFIG:
        return list(PRODUCTION_CONFIG[key_low])

    # Final fallback: default chain with equal weights
    n = 3
    w = round(1.0 / n, 2)
    return [
        StrategyConfig(name, weight=w)
        for name in DEFAULT_FALLBACK_CHAIN[:n]
    ]
